#!/bin/bash    
# chmod a+x /where/i/saved/it/foundryInstall.sh
# Instalação do Foundry na Oracle
# Atualiza o sistema e remove pacotes antigos
sudo apt update && sudo apt upgrade -y && sudo apt autoremove -y && sudo apt autoclean
#Atualiza o iptables para abrir portas 80, 443, 30000
sudo iptables -I INPUT 6 -m state --state NEW -p tcp --match multiport --dports 80,443,30000 -j ACCEPT
# salva esta config
sudo netfilter-persistent save
# instala nodejs, pm2, nano, unzip
sudo apt install curl nano unzip -y
curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
sudo apt install -y nodejs
sudo npm install pm2 -g
sudo npm update -g pm2
sudo pm2 update
#permite pm2 para iniciar apos o reboot
pm2 startup
sudo env PATH=$PATH:/usr/bin /usr/lib/node_modules/pm2/bin/pm2 startup systemd -u ubuntu --hp /home/ubuntu
# cria as pastas necessarias
mkdir ~/foundry
mkdir ~/foundryuserdata
# Instala caddy para configuracao reverse proxy e https
sudo apt install -y debian-keyring debian-archive-keyring apt-transport-https
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | sudo gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' | sudo tee /etc/apt/sources.list.d/caddy-stable.list
sudo apt update
sudo apt install caddy
# Adiciona Foundry timed url para download
echo "Insira o timed download url do Foundry versão NodeJS"
read tdurl
wget --output-document ~/foundry/foundryvtt.zip "$tdurl"
unzip ~/foundry/foundryvtt.zip -d ~/foundry/
rm ~/foundry/foundryvtt.zip
# Configura pm2 para iniciar foundry vtt no inicio e reinicio do sistema.
pm2 start "node /home/ubuntu/foundry/resources/app/main.js --dataPath=/home/ubuntu/foundryuserdata" --name foundry
pm2 save
# Configura Caddy reverse proxy
curl -o Caddyfile https://raw.githubusercontent.com/aco-rt/Foundry-VTT-Oracle/main/Caddyfile
sudo rm /etc/caddy/Caddyfile
sudo mv Caddyfile /etc/caddy/Caddyfile
echo "Insira url do dominio"
read vtturl
sudo sed -i "s/your.hostname.com/$vtturl/g" /etc/caddy/Caddyfile
sudo service caddy restart
# Edita arquivo foundry options.json para permitir conexões pelo proxy e porta 443
sed -i 's/"proxyPort": null/"proxyPort": 443/g' /home/ubuntu/foundryuserdata/Config/options.json
sed -i 's/"proxySSL": false/"proxySSL": true/g' /home/ubuntu/foundryuserdata/Config/options.json
sed -i 's/"hostname": null/"hostname": "$vtturl"/g' /home/ubuntu/foundryuserdata/Config/options.json
# Reinicia o sistema para completar a instalação
sleep 2
clear
echo "Reiniciando o sistema para completar a instalação"
sleep 3
sudo shutdown -r now
